version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: stego_backend
    restart: unless-stopped
    environment:
      - PORT=8080 # Backend sẽ chạy ở port 8080 bên trong container

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: stego_frontend
    restart: unless-stopped
    ports:
      - "80:80" # Ánh xạ port 80 của máy chủ EC2 vào port 80 của container Nginx
    depends_on:
      - backend