# --- STAGE 1: Build ---
FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY stego-app/go.mod stego-app/go.sum ./
RUN go mod download

COPY stego-app/ .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o stego-app .


# --- STAGE 2: Deploy ---
FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/stego-app .

EXPOSE 8080

CMD ["./stego-app"]